from fastapi import APIRouter, Depends, HTTPException
from typing import List
from models.schemas import RunEvent, RunStats
from core.config import settings
from core.database import get_supabase
from supabase import Client
import os
import time

router = APIRouter(prefix="/runs", tags=["Runs"])

@router.get("/", response_model=List[dict])
async def list_runs(supabase: Client = Depends(get_supabase)):
    """Returns all recent autonomous runs from Supabase."""
    if not supabase:
        return []
    
    response = supabase.table("runs").select("*").order("created_at", desc=True).limit(50).execute()
    return response.data

@router.get("/stats")
async def get_stats(supabase: Client = Depends(get_supabase)):
    """Returns aggregated dashboard statistics."""
    if not supabase:
        # Fallback to mock-like stats if no DB connection
        return {
            "arr_percent": 0.0,
            "avg_mttr_seconds": 0.0,
            "avg_mttr_display": "0m 00s",
            "active_sandboxes": 0,
            "max_sandboxes": 200,
            "bugs_fixed_month": 0,
            "total_runs_month": 0,
        }

    # Stats aggregation from real telemetry
    runs_res = supabase.table("runs").select("status, mttr_seconds").execute()
    runs = runs_res.data
    
    completed = [r for r in runs if r["status"] == "completed"]
    total = len(runs)
    arr = (len(completed) / total * 100) if total > 0 else 0
    
    mttrs = [r["mttr_seconds"] for r in completed if r.get("mttr_seconds")]
    avg_mttr = sum(mttrs) / max(len(mttrs), 1)

    return {
        "arr_percent": round(arr, 1),
        "avg_mttr_seconds": round(avg_mttr, 1),
        "avg_mttr_display": f"{int(avg_mttr // 60)}m {int(avg_mttr % 60):02d}s",
        "active_sandboxes": 1, # Placeholder, in a real system we'd query sandbox_manager
        "max_sandboxes": 200,
        "bugs_fixed_month": len(completed),
        "total_runs_month": total,
    }

@router.get("/{run_id}")
async def get_run(run_id: str, supabase: Client = Depends(get_supabase)):
    """Returns details for a specific run."""
    if not supabase:
        raise HTTPException(status_code=500, detail="Database connection not available")
        
    response = supabase.table("runs").select("*").eq("id", run_id).single().execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Run not found")
        
    
    return response.data

@router.post("/{run_id}/apply")
async def apply_fix(run_id: str, supabase: Client = Depends(get_supabase)):
    """
    Triggers the creation of a GitHub Pull Request for a completed repair.
    """
    if not supabase:
        raise HTTPException(status_code=500, detail="Database connection not available")

    # 1. Fetch run details
    run_res = supabase.table("runs").select("*").eq("id", run_id).single().execute()
    run = run_res.data
    if not run:
        raise HTTPException(status_code=404, detail="Run not found")

    if not run.get("sandbox_id") or not run.get("repo"):
        raise HTTPException(status_code=400, detail="Run lacks infrastructure data to apply fix")

    # 2. Push changes to a new branch
    branch_name = f"devcure/fix-{run_id}"
    sandbox_path = os.path.join(settings.SANDBOX_BASE_PATH, run["sandbox_id"])
    
    success = github_service.push_changes(sandbox_path, run["repo"], branch_name)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to push changes to GitHub")

    # 3. Create Pull Request
    pr_url = await github_service.create_pull_request(
        repo_full_name=run["repo"],
        title=f"DevCure Auto-Fix: {run_id}",
        body=f"This Pull Request was autonomously generated by DevCure AI.\n\n### Diagnosis:\n{run.get('diagnosis', 'No diagnosis available')}",
        head=branch_name,
        base=run.get("branch", "main")
    )

    if not pr_url:
        raise HTTPException(status_code=500, detail="Failed to open Pull Request on GitHub")

    # 4. Update Supabase
    supabase.table("runs").update({
        "status": "completed",
        "pr_url": pr_url
    }).eq("id", run_id).execute()

    return {"status": "success", "pr_url": pr_url}
